export default {
    BASIC_ACTION: "BASIC_ACTION",
    BASIC_ACTION_SUCCESS: "BASIC_ACTION_SUCCESS",
    BASIC_ACTION_ERROR: "BASIC_ACTION_ERROR",

    CREATE_EGO: "CREATE_EGO",
    CHOOSE_EGO: "CHOOSE_EGO",
    CHOOSE_CONVERSER: "CHOOSE_CONVERSER",

    MESSAGE_SEND: "MESSAGE_SEND",
    MESSAGE_READ: "MESSAGE_READ"
};